#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

source $HOME/.config/bspwm/exec.sh

# bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor -d 1 2 3 4 5 6 7 8 9 0
bspc monitor -d 1 2 3 4 5
#bspc monitor -d         

bspc config border_width         2
bspc config focused_border_color "#9999ff"
bspc config window_gap           4
bspc config focus_follows_pointer true

bspc config top_padding          0
bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Rofi focus=on



